name: Deploy_ISS_App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "devopsexercise_v2" #Must be unique in Heroku
          heroku_email: "flyingstick22@gmail.com"
          usedocker: true
